# https://taskfile.dev

version: '3'

tasks:
  prepare:
    cmds:
      - terraform fmt -recursive

  bootstrap:
    deps: ["prepare"]
    dir: ./bootstrap
    cmds:
      - terraform init
      - terraform validate
      - terraform apply

  plan:
    deps: ["prepare"]
    #dir: ./root-namespace
    dir: ./baseline-configuration
    cmds:
      - terraform init
      - terraform plan
